/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateNewExpenseImport } from './routes/createNewExpense'
import { Route as AllExpensesImport } from './routes/allExpenses'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateNewExpenseRoute = CreateNewExpenseImport.update({
  id: '/createNewExpense',
  path: '/createNewExpense',
  getParentRoute: () => rootRoute,
} as any)

const AllExpensesRoute = AllExpensesImport.update({
  id: '/allExpenses',
  path: '/allExpenses',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/allExpenses': {
      id: '/allExpenses'
      path: '/allExpenses'
      fullPath: '/allExpenses'
      preLoaderRoute: typeof AllExpensesImport
      parentRoute: typeof rootRoute
    }
    '/createNewExpense': {
      id: '/createNewExpense'
      path: '/createNewExpense'
      fullPath: '/createNewExpense'
      preLoaderRoute: typeof CreateNewExpenseImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allExpenses': typeof AllExpensesRoute
  '/createNewExpense': typeof CreateNewExpenseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allExpenses': typeof AllExpensesRoute
  '/createNewExpense': typeof CreateNewExpenseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/allExpenses': typeof AllExpensesRoute
  '/createNewExpense': typeof CreateNewExpenseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/allExpenses' | '/createNewExpense'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/allExpenses' | '/createNewExpense'
  id: '__root__' | '/' | '/about' | '/allExpenses' | '/createNewExpense'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AllExpensesRoute: typeof AllExpensesRoute
  CreateNewExpenseRoute: typeof CreateNewExpenseRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AllExpensesRoute: AllExpensesRoute,
  CreateNewExpenseRoute: CreateNewExpenseRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/allExpenses",
        "/createNewExpense"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/allExpenses": {
      "filePath": "allExpenses.tsx"
    },
    "/createNewExpense": {
      "filePath": "createNewExpense.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
